### `r fontawesome::fa("cogs", fill = "steelblue")` Présentation

**LinkR** est une application web permettant de visualiser et d'analyser des données de santé.

L'application est codée en R avec la librairie Shiny.

Elle utilise le modèle de données commun [OMOP](https://ohdsi.github.io/CommonDataModel/).

### `r fontawesome::fa("users", fill = "steelblue")` À qui s'adresse l'application ?

L'application s'adresse :

- **aux cliniciens**, une interface intuitive permet aux cliniciens d'analyser les données et de mener des études sans connaissances avancées en programmation
- **aux data scientists et statisticiens**, LinkR offre un accès à un environnement R complet, permettant aux data scientists et aux statisticiens d'exploiter toutes les fonctionnalités d'analyse de données avancées
- **aux étudiants en santé**, des tutoriels intégrés à l'application offrent aux étudiants en santé une opportunité d'apprendre et de pratiquer l'analyse des données dans le domaine de la santé

LinkR facilite ainsi le **travail collaboratif**.

### `r fontawesome::fa("share-alt", fill = "steelblue")` Partage et open science

LinkR est une application **open source**.

Elle contribue à l'**open science** en permettant le partage :

- *d'études* : importez et exportez vos études en un clic, reproduisez des études avec vos propres données
- *de scripts* : partagez des scripts interopérables, grâce à l'utilisation du modèle commun de données OMOP
- *de plugins* : aidez à améliorer l'application en créant des plugins et en les partageant

### `r fontawesome::fa("code-branch", fill = "steelblue")` Contributions

LinkR a **besoin de vous** pour évoluer !

Vous pouvez contribuer en créant des plugins, ou en aidant à améliorer le code de l'application.

### `r fontawesome::fa("gift", fill = "steelblue")` Soutenez-nous

LinkR est proposé par l'association **Interhop**, promouvant l'open-source et l'interopérabilité en santé.

Vous pouvez [faire un don ici](https://interhop.org/dons/).

### `r fontawesome::fa("exclamation-triangle", fill = "steelblue")` Signalez un bug

[Rendez-vous ici](https://github.com/BorisDelange/LinkR/issues) pour signaler un bug.

### `r fontawesome::fa("envelope", fill = "steelblue")` Contact

Email : contact@email.com

Discussions on github ?