### Présentation

**LinkR** est une application web codée en *R - Shiny* visant à **faciliter l'utilisation** des données issues d'**entrepôts de données de santé** (EDS).

En effet, manipuler les données d'EDS nécessité des connaissances poussées en programmation (R, Python, SQL).

L'application permet, grâce à une **interface graphique** simple d'utilisation, de **réaliser des études** sur des données issues d'EDS **sans connaissance en programmation**.

Pour autant, il est tout de même possible de manipuler les données avec **R, Python et SQL** depuis l'application.

L'application a vocation à s'**enrichir** progressivement par le développement et le partage de **plugins**.

Le schéma de données est celui d'[**OMOP**](https://ohdsi.github.io/CommonDataModel/cdm60.html).

### Mise en place

Des **données par défaut** issues de la base de données **MIMIC-IV** sont chargées lors de la première utilisation de l'application.

Vous pouvez **charger ces données** depuis la page *Données*, en haut de l'écran.

L'onglet *Mise en place* à gauche de l'écran vous explique les différentes étapes permettant de **charger des données** et de **créer une première étude**.

### Pages d'aide

Chaque page de l'application comporte **une aide**, à laquelle vous accédez via le point d'interrogation en haut à droite de l'écran.

### Signaler un bug

Pour signaler un bug, rendez-vous sur ... `r fontawesome::fa("fas fa-book")`
